# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterCopy',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('novelname', models.CharField(max_length=100)),
                ('novelimg', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovelCopy',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('novelname', models.CharField(max_length=100)),
                ('novelimg', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel_copy',
                'managed': False,
            },
        ),
    ]
